{% set name = "xoa" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xoa-{{ version }}.tar.gz
  sha256: c6b1b1cc2731f98d7f17539aa3a58755d1f6842ad9372495d2e6a79aa8e583db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=40.4
    - setuptools-scm
  run:
    - appdirs
    - cmocean
    - configobj
    - gsw
    - netcdf4
    - numba
    - python >={{ python_min }}
    - scipy
    - setuptools >=40.4
    - xarray

test:
  source_files:
    - xoa/tests/*
  imports:
    - xoa
  commands:
    - pip check
#    - xoa info
    - pytest xoa/tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/shom-fr/xoa
  summary: xarray-based ocean analysis library
  license: Apache-2.0
  license_file: LICENSE
  description: |
    xoa is intended to help reading and manipulating observed and
    simulated ocean data. It is heavily based on xarray.
  doc_url: https://xoa.readthedocs.io/
  dev_url: https://github.com/shom-fr/xoa

extra:
  recipe-maintainers:
    - stefraynaud
    - mmorvan
