{% set name = "xoa" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xoa-{{ version }}.tar.gz
  sha256: 755d7913bd3730893f464d2e1d27ec46cd8970c36a71fa00bb9bfb079c2372d3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=40.4
    - setuptools-scm
  run:
    - appdirs
    - cmocean
    - configobj
    - gsw
    - netcdf4
    - numba
    - python >=3.7
    - scipy
    - setuptools >=40.4
    - xarray

test:
  source_files:
    - xoa/tests/*
  imports:
    - xoa
  commands:
    - pip check
#    - xoa info
    - pytest xoa/tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/shom-fr/xoa
  summary: xarray-based ocean analysis library
  license: Apache-2.0
  license_file: LICENSE
  description: |
    xoa is intended to help reading and manipulating observed and
    simulated ocean data. It is heavily based on xarray.
  doc_url: https://xoa.readthedocs.io/
  dev_url: https://github.com/shom-fr/xoa

extra:
  recipe-maintainers:
    - stefraynaud
